[package]
name = "lib-infrastructure"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[features]
persistence = ["dep:persistence"]
persistence-postgres = ["persistence", "persistence/postgres"]

[dependencies]
persistence = { path = "./persistence", package = "lib-infrastructure-persistence", optional = true }

[lints]
workspace = true
