edition = "2024"
match_block_trailing_comma = true
max_width = 80
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_lit_single_line = false
style_edition = "2024"
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
