[package]
name = "template_example-presentation-api-rest"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
lib = { workspace = true, features = ["presentation-api-rest-openapi"] }
domain = { path = "../../../domain", package = "template_example-domain" }
application = { path = "../../../application", package = "template_example-application" }

axum = { workspace = true, features = ["macros"] }
redact = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
utoipa = { workspace = true, features = [
  "axum_extras",
  "preserve_order",
  "preserve_path_order",
  "non_strict_integers",
  "uuid",
  "chrono",
  "url",
] }

axum-extra = { version = "0.12", features = ["typed-header"] }
derive_more = { version = "2.1", features = ["from", "into"] }

[lints]
workspace = true
