[package]
name = "lib-infrastructure-persistence-postgres"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
sqlx = { workspace = true, features = ["runtime-tokio", "postgres", "uuid"] }
tap.workspace = true
thiserror.workspace = true


[lints]
workspace = true
