[package]
name = "lib-presentation-api-rest"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
domain = { path = "../../../domain", package = "lib-domain" }

axum.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["signal"] }
tower.workspace = true
tracing.workspace = true
utoipa.workspace = true
utoipa-axum.workspace = true
utoipa-scalar = { workspace = true, features = ["axum"] }

tower-http = { version = "0.6" , features = ["catch-panic" ] }

[lints]
workspace = true
