[package]
name = "lib-presentation-api-rest"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[features]
openapi = ["dep:utoipa", "dep:utoipa-scalar"]

[dependencies]
domain = { path = "../../../domain", package = "lib-domain" }

axum = { workspace = true, features = ["macros"] }
chrono = { workspace = true, features = ["serde"] }
opentelemetry = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tap.workspace = true
tokio = { workspace = true, features = ["signal"] }
tower.workspace = true
tower-http = { workspace = true, features = [
  "catch-panic",
  "request-id",
  "trace",
] }
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa = { workspace = true, optional = true }
uuid.workspace = true

tracing-otel-extra = { version = "0.30", features = [
  "context",
  "fields",
  "macros",
] }
utoipa-scalar = { version = "0.3", optional = true, features = ["axum"] }

[dev-dependencies]
rstest.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["test-util"] }

serde_urlencoded = "0.7"


[lints]
workspace = true
