[package]
name = "template_example-infrastructure-services-hasher-argon2"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
lib = { workspace = true }
application = { path = "../../../../application", package = "template_example-application" }

anyhow.workspace = true
redact.workspace = true
thiserror.workspace = true
tracing.workspace = true

argon2 = { version = "0.5", features = ["std"] }

[lints]
workspace = true
