[package]
name = "lib-presentation"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[features]
api = ["dep:api"]
api-rest = ["api", "api/rest"]
api-rest-openapi = ["api-rest", "api/rest-openapi"]

bot = ["dep:bot"]
bot-telegram = ["bot", "bot/telegram"]

[dependencies]
api = { path = "./api", package = "lib-presentation-api", optional = true }
bot = { path = "./bot", package = "lib-presentation-bot", optional = true }

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
