[package]
name = "lib-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
derive-where.workspace = true
uuid = { workspace = true, features = ["v7"] }

num-traits = "0.2.19"
regex = "1.12.2"

[dev-dependencies]
rstest = { workspace = true }
tokio = { workspace = true }
