[package]
name = "lib-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
derive-where.workspace = true
num-traits = "0.2"
tap.workspace = true
uuid = { workspace = true, features = ["v7"] }

regex = "1.12"

[dev-dependencies]
rstest = { workspace = true }
tokio = { workspace = true }
