[package]
name = "lib-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
bon.workspace = true
derive-where.workspace = true
pastey.workspace = true
serde.workspace = true
serde-value.workspace = true
uuid = { workspace = true, features = ["v7", "serde"] }

num-traits = "0.2"
regex = "1.12"
validator-rs = "0.1"


[dev-dependencies]
rstest = { workspace = true }
tokio = { workspace = true }


[lints]
workspace = true
