target: all
multitenancy_enabled: false
common:
  storage:
    backend: s3
    s3:
      endpoint: s3:9000
      access_key_id: minioadmin
      secret_access_key: minioadmin
      insecure: true
      bucket_name: mimir
blocks_storage:
  storage_prefix: blocks
server:
  http_listen_port: 9009
  log_level: warn
ingester:
  ring:
    replication_factor: 1
limits:
  enabled_promql_experimental_functions: info
  otel_metric_suffixes_enabled: true
  otel_created_timestamp_zero_ingestion_enabled: true
  otel_keep_identifying_resource_attributes: true
  promote_otel_resource_attributes: "service.instance.id, service.name, service.namespace, service.version, cloud.availability_zone, cloud.region, container.name, deployment.environment, deployment.environment.name, k8s.cluster.name, k8s.container.name, k8s.cronjob.name, k8s.daemonset.name, k8s.deployment.name, k8s.job.name, k8s.namespace.name, k8s.pod.name, k8s.replicaset.name, k8s.statefulset.name"
