global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "otel-collector-prometheus"
    static_configs:
      - targets: ["otel-collector:9090"]
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: "mimir"
    static_configs:
      - targets: ["mimir:9009"]
  - job_name: "minio"
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["s3:9000"]
  - job_name: "minio-bucket"
    metrics_path: /minio/v2/metrics/bucket
    static_configs:
      - targets: ["s3:9000"]
remote_write:
  - url: "http://mimir:9009/api/v1/push"
    remote_timeout: 30s
    write_relabel_configs:
      - source_labels: [__name__]
        regex: ".*"
        action: keep
