global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888"]
  - job_name: "victoria-logs"
    static_configs:
      - targets: ["victoria-logs:9428"]
  - job_name: "victoria-traces"
    static_configs:
      - targets: ["victoria-traces:10428"]
