[package]
name = "template_example-domain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
lib = { workspace = true, features = ["domain", "macros-proc"] }

thiserror.workspace = true

[lints]
workspace = true
